version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - DATABASE_URL=mysql://root:root@mysql_db:3306/hospital_db

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: hospital_db        
      MYSQL_USER: myuser                 
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
