"""nullable is False for patient_id in patient_assistant

Revision ID: 1eb20099b30a
Revises: 95c74f5e1c91
Create Date: 2025-03-11 10:30:04.875133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eb20099b30a'
down_revision = '95c74f5e1c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_assistants', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_assistants', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
