"""added column for later statistics

Revision ID: debbd70a4a90
Revises: 1eb20099b30a
Create Date: 2025-03-11 10:39:21.280609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debbd70a4a90'
down_revision = '1eb20099b30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescribed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_treatments', schema=None) as batch_op:
        batch_op.drop_column('prescribed_at')

    # ### end Alembic commands ###
